# Generated by Django 3.1.6 on 2021-02-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('box_number', models.CharField(max_length=5)),
                ('d1', models.CharField(max_length=5)),
                ('d2', models.CharField(max_length=5)),
                ('d3', models.CharField(max_length=5)),
                ('d4', models.CharField(max_length=5)),
                ('d5', models.CharField(max_length=5)),
                ('d6', models.CharField(max_length=5)),
            ],
        ),
    ]
