# Generated by Django 3.1.6 on 2021-03-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='d1',
            field=models.DateTimeField(),
        ),
    ]
