# Generated by Django 3.1.6 on 2021-03-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20210304_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db',
            name='d1',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='db',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
